### ISSUE TITLE
Custom domain support

### ISSUE THREAD

**Issue by iotech-fvtt** [entvex/NgrokGUI#20]
This is a great tool, but currently of no use to me. I have a paid ngrok account and do not use subdomains, but rather custom domains
i.e. bninding a tunnel to a fully qualified domain name that I control like "web.maydomain.com"

https://ngrok.com/docs/guides/how-to-set-up-a-custom-domain
 

Please add support for custom domains - its just another command-line switch like "ngrok http[s] -hostname=foo.example.com [port]".

**Comment by entvex** [comment]
Dear @iotech-fvtt
Thanks so much for the feature request!

I'll start looking into this issue next week.

**Comment by entvex** [comment]
The code should be added in NgrokSharp. Now I'll work on added it to NgrokGUI.

**Comment by iotech-fvtt** [comment]
Thanks, entvex! That's great news!

**Comment by entvex** [comment]
@iotech-fvtt I have added code to support tunnels on custom branded domains. I'll make a new release soon, and then you can download it in the release's section on GitHub 👍

**Comment by entvex** [comment]
Dear @iotech-fvtt Now you can download the new release at https://github.com/entvex/NgrokGUI/releases/tag/1.0.3
