### ISSUE TITLE
Installer crash

### ISSUE THREAD

**Issue by iotech-fvtt** [entvex/NgrokGUI#22]
Today's release, downloaded exe, get attached error on start (normal or RunAs Administrator)
![explorer_oDM56DGqAm](https://user-images.githubusercontent.com/29070865/157569780-b0a0a7a1-adf5-4ddd-8b14-91e9ce9f27ba.png)

Windows 10
16GB
Ryzen 5

**Comment by entvex** [comment]
Dear @iotech-fvtt 

If you start run, by pressing the windows key + r and type %appdata%\NgrokSharp and click ok now a folder should open

![image](https://user-images.githubusercontent.com/1580435/157628245-e3d9eb7e-812b-4fb5-a4e0-1c97db91aa8f.png)

Can you delete everything in that folder and start the application again ?

Greetings David

**Comment by iotech-fvtt** [comment]
All working after the above. Thanks, David!!

**Comment by entvex** [comment]
I am happy, that it worked for you 😄. If you like my open source project, please consider giving it a ⭐.
I hope you have a very good day.
