### ISSUE TITLE
downloading ngrok not working

### ISSUE THREAD

**Issue by PawnStorm0x** [entvex/NgrokGUI#24]
the first step ngrok download don't work

**Comment by entvex** [comment]
Dear @PawnStorm0x 

I have just tried to use the application. And it did the download step and it completed jsut fine.

Can you please add
Screenshots If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):
    OS: [e.g. Windows 10]
    Version [e.g. 22]

Thanks in advance

**Comment by entvex** [comment]
@PawnStorm0x Do you still have an issue? Please respond or I'll close this issue.

**Comment by PawnStorm0x** [comment]
hello yes  solved i download ngrok manually and run again worked and pass the first step

**Comment by entvex** [comment]
Sounds good @PawnStorm0x. Let me know if there are other issues. :)
