### ISSUE TITLE
Add subdomain option

### ISSUE THREAD

**Issue by vihatsoft** [entvex/NgrokGUI#7]
thank you for nice app.
 please add subdomain option like:
 ngrok http -subdomain domainName 80

thank you,

**Comment by entvex** [comment]
Hello @vihatsoft 
Thanks for your suggestion.
Do you see this as a command-line option or in the gui ?

**Comment by vihatsoft** [comment]
bellow is command line not in GUI
"ngrok http -subdomain domainName 80"

this command use for create tunnel with specific subdomain for ngrock paid customer.

**Comment by entvex** [comment]
@vihatsoft Thanks for the fast response :)!
This is a good feature request. I will reach out to ngrok and ask if i am allowed to have paid account for testing. If they allow that, then it will be easier to implement and test the paid features :)

**Comment by vihatsoft** [comment]
okay, thank you

**Comment by entvex** [comment]
Dear @vihatsoft.
The people at Ngrok, was super nice and provided me with a Ngrok account I can use for testing when implementing the paid features of Ngrok in ngrokGUI. I don't have an ETA for the subdomain option, but rest assure, it is in the backlog now. And i will look into it :)

**Comment by vihatsoft** [comment]
okay bro.. thank you 👍

**Comment by vihatsoft** [comment]
* when first time start custom subdomain tunnel then automatically save information for start in feature without enter subdomain and port information. only right click to start and stop if already active. thank you

**Comment by entvex** [comment]
Dear @vihatsoft 
If you know, how to do it, you can take a look at the branch [AllowUserToCreateTunnelWithSubDomain](https://github.com/entvex/NgrokGUI/tree/AllowUserToCreateTunnelWithSubDomain) and compile the program. It should now, allow you to create tunnels with subdomains, if you have a paid auth token. I still need to work on it a bit more, before i make a new release.

**Comment by vihatsoft** [comment]
okay i will try tomorrow and reply soon as possible..

**Comment by entvex** [comment]
@vihatsoft I'll soon make a release with the new features. Now it is all in the main branch 👍

**Comment by vihatsoft** [comment]
when will release new version? i am waiting...

**Comment by entvex** [comment]
@vihatsoft right here https://github.com/entvex/NgrokGUI/releases/tag/1.0.1

**Comment by vihatsoft** [comment]
Perfect 👍

**Comment by vihatsoft** [comment]
perfect but, if i choose india then tunnel start with domain.in.ngrok.io.. so, add none option while choose data centre. so if choose none then tunnel start with domain.ngrok.io means without region code.

**Comment by entvex** [comment]
Thanks!
Your Ngrok sub domain belong to the data center toy choose. If you would like to use "domain.ngrok.io" Then you have to use united states.

I hope it makes sense, if not feel free to ask again :)

**Comment by vihatsoft** [comment]
okay bro... thank
